#configuration for makefile
#So that makefile stays largely despite the same despite the libraries being used

#High-level libraries used
#Must specify both the sub-folder levels
#and the files themselves
#	eg. HL_LIBS += blargh.c

#HL_LIBS += usbSerial.c

HL_LIBS_CPP += $(ROOT)main.cpp

SUBHIGH += -I lib
HL_LIBS_CPP += lib/protocol/drawing/drawing.cpp
HL_LIBS_CPP += lib/periph/i2c/i2cMaster.cpp
HL_LIBS_CPP += lib/devices/ssd1306/ssd1306.cpp











#HL_LIBS += $(ROOT)configuration.c

#HL_LIBS += $(LOWLEVEL)/serial.c

#general things
#HL_LIBS += $(MIDLEVEL)/commandHandler.c


#add a subfolder
#SUBHIGH += $(HIGHLEVEL)/folder
#HL_LIBS += $(HIGHLEVEL)/folder/blargh.c


#SUBHIGH += .
SUBMID += include
#HL_LIBS += src/serialServo/serialServoSlave.c
#HL_LIBS += src/serialServo/serialServoMaster.c
#HL_LIBS += src/serialServo/serialServoCommon.c
#HL_LIBS += src/i2c/i2cMaster.c
#HL_LIBS += src/pca9685/pca9685.c
